nodes:
- asset_type: stock
  base_filters:
  - field: security_type
    op: '='
    value: EXTRA_STOCK_A
  description: 股票日线行情主表
  description_zh: null
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: daily
  name: stock_daily_real
  node_role: query_entry
  physical_node: null
  query_freq: 1d
  status: enabled
  table: starlight.ad_market_kline_daily
  time_key: trade_time
- asset_type: stock
  base_filters: []
  description: null
  description_zh: 股票分钟行情主表
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: minute
  name: stock_minute_real
  node_role: query_entry
  physical_node: null
  query_freq: 1m
  status: enabled
  table: starlight.ad_market_kline_minute
  time_key: trade_time
- asset_type: null
  base_filters: []
  description: null
  description_zh: 行业日线行情表
  entity_keys:
  - index_code
  fields:
  - index_code
  - trade_date
  - open
  - high
  - close
  - low
  - amount
  - volume
  - pb
  - pe
  - total_cap
  - a_float_cap
  - pre_close
  grain: daily
  name: industry_daily_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_industry_daily
  time_key: trade_date
- asset_type: null
  base_filters: []
  description: null
  description_zh: 国债收益率表
  entity_keys:
  - term
  fields:
  - term
  - trade_date
  - yield_value
  grain: daily
  name: treasury_yield_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_treasury_yield
  time_key: trade_date
- asset_type: null
  base_filters: []
  description: null
  description_zh: 基金 IOPV 表
  entity_keys:
  - market_code
  fields:
  - market_code
  - price_date
  - iopv_nav
  grain: daily
  name: fund_iopv_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_fund_iopv
  time_key: price_date
- asset_type: null
  base_filters: []
  description: null
  description_zh: 基金份额表
  entity_keys:
  - market_code
  fields:
  - market_code
  - fund_share
  - change_reason
  - is_consolidated_data
  - ann_date
  - total_share
  - change_date
  - float_share
  grain: daily
  name: fund_share_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_fund_share
  time_key: ann_date
- asset_type: null
  base_filters: []
  description: null
  description_zh: ETF PCF 主表
  entity_keys:
  - etf_code
  fields:
  - etf_code
  - creation_redemption_unit
  - max_cash_ratio
  - publish
  - creation
  - redemption
  - creation_redemption_switch
  - record_num
  - total_record_num
  - estimate_cash_component
  - trading_day
  - pre_trading_day
  - cash_component
  - nav_per_cu
  - nav
  - symbol
  - fund_management_company
  - underlying_security_id
  - underlying_security_id_source
  - dividend_per_cu
  - creation_limit
  - redemption_limit
  - creation_limit_per_user
  - redemption_limit_per_user
  - net_creation_limit
  - net_redemption_limit
  - net_creation_limit_per_user
  - net_redemption_limit_per_user
  grain: daily
  name: etf_pcf_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_etf_pcf
  time_key: trading_day
- asset_type: null
  base_filters: []
  description: null
  description_zh: 可转债发行表
  entity_keys:
  - market_code
  fields:
  - market_code
  - stock_code
  - crncy_code
  - ann_dt
  - pre_plan_date
  - smtg_ann_date
  - listed_ann_date
  - listed_date
  - plan_schedule
  - is_separation
  - recommender
  - clause_is_int_cha_de_po_rate
  - clause_is_com_int
  - clause_com_int_rate
  - clause_com_int_desc
  - clause_init_conv_price_item
  - clause_conv_adj_item
  - clause_conv_period_item
  - clause_ini_conv_price
  - clause_ini_conv_premium_ratio
  - clause_put_item
  - clause_call_item
  - clause_spec_down_adj
  - clause_orig_ration_arr_item
  - list_pass_date
  - list_permit_date
  - list_ann_date
  - list_result_ann_date
  - list_type
  - list_fee
  - list_ration_date
  - list_ration_reg_date
  - list_ration_paymt_date
  - list_ration_code
  - list_ration_name
  - list_ration_price
  - list_ration_ratio_de
  - list_ration_ratio_mo
  - list_ration_vol
  - list_household
  - list_onl_date
  - list_pchase_code_onl
  - list_pch_name_onl
  - list_pch_price_onl
  - list_issue_vol_onl
  - list_code_onl
  - list_excess_pch_onl
  - result_ef_subscr_p_off
  - result_suc_rate_off
  - list_date_inst_off
  - list_vol_inst_off
  - result_suc_rate_on
  - list_effect_pc_hvol_off
  - list_eff_pc_h_of
  - list_suc_rate_off
  - pre_ration_vol
  - list_issue_size
  - list_issue_quantity
  - min_off_inst_subscr_qty
  - off_inst_dep_ratio
  - max_off_inst_subscr_qty
  - off_subscr_unit_inc_desc
  - is_conv_bonds
  - min_unline_public
  - max_unline_public
  - term_year
  - interest_type
  - coupon_rate
  - interest_fre_quency
  - result_suc_rate_on2
  - coupon_txt
  - ratio_annce_date
  - ratio_date
  grain: daily
  name: kzz_issuance_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_kzz_issuance
  time_key: ann_dt
- asset_type: null
  base_filters: []
  description: null
  description_zh: 可转债转股规则表
  entity_keys:
  - market_code
  fields:
  - market_code
  - ann_date
  - conv_code
  - conv_name
  - conv_price
  - currency_code
  - conv_start_date
  - conv_end_date
  - trade_date_last
  - forced_conv_date
  - forced_conv_price
  - rel_conv_month
  - is_forced
  - forced_conv_reason
  grain: daily
  name: kzz_conv_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_kzz_conv
  time_key: ann_date
- asset_type: null
  base_filters: []
  description: null
  description_zh: 融资融券市场汇总表
  entity_keys: []
  fields:
  - trade_date
  - sum_borrow_money_balance
  - sum_purch_with_borrow_money
  - sum_repayment_of_borrow_money
  - sum_sec_lending_balance
  - sum_sales_of_borrowed_sec
  - sum_margin_trade_balance
  grain: daily
  name: margin_summary_real
  node_role: query_entry
  physical_node: null
  query_freq: null
  status: enabled
  table: starlight.ad_margin_summary
  time_key: trade_date
- asset_type: etf
  base_filters:
  - field: security_type
    op: '='
    value: EXTRA_ETF
  description: null
  description_zh: ETF日线逻辑入口
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: daily
  name: etf_daily_real
  node_role: query_entry
  physical_node: stock_daily_real
  query_freq: 1d
  status: enabled
  table: starlight.ad_market_kline_daily
  time_key: trade_time
- asset_type: index
  base_filters:
  - field: security_type
    op: '='
    value: EXTRA_INDEX_A_SH_SZ
  description: null
  description_zh: 指数日线逻辑入口
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: daily
  name: index_daily_real
  node_role: query_entry
  physical_node: stock_daily_real
  query_freq: 1d
  status: enabled
  table: starlight.ad_market_kline_daily
  time_key: trade_time
- asset_type: etf
  base_filters: []
  description: null
  description_zh: ETF分钟逻辑入口
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: minute
  name: etf_minute_real
  node_role: query_entry
  physical_node: stock_minute_real
  query_freq: 1m
  status: enabled
  table: starlight.ad_market_kline_minute
  time_key: trade_time
- asset_type: index
  base_filters: []
  description: null
  description_zh: 指数分钟逻辑入口
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: minute
  name: index_minute_real
  node_role: query_entry
  physical_node: stock_minute_real
  query_freq: 1m
  status: enabled
  table: starlight.ad_market_kline_minute
  time_key: trade_time
edges:
- bridge_steps: []
  description: null
  description_zh: stock_daily_real 到 etf_pcf_real，按同日关联
  from_node: stock_daily_real
  join_keys:
  - base: code
    source: etf_code
  name: stock_daily_real_to_etf_pcf_real
  priority: 100
  relation_type: direct
  source_table: null
  time_binding:
    allow_equal: true
    available_time_field: null
    base_time_cast: date
    base_time_field: trade_time
    lookahead_safe: true
    mode: same_date
    source_end_field: null
    source_start_field: null
    source_time_cast: null
    source_time_field: trading_day
  to_node: etf_pcf_real
  from: stock_daily_real
  to: etf_pcf_real
- bridge_steps: []
  description: null
  description_zh: stock_daily_real 到 kzz_issuance_real，按截至时点关联
  from_node: stock_daily_real
  join_keys:
  - base: code
    source: market_code
  name: stock_daily_real_to_kzz_issuance_real
  priority: 100
  relation_type: direct
  source_table: null
  time_binding:
    allow_equal: true
    available_time_field: null
    base_time_cast: date
    base_time_field: trade_time
    lookahead_safe: true
    mode: asof
    source_end_field: null
    source_start_field: null
    source_time_cast: yyyymmdd
    source_time_field: ann_dt
  to_node: kzz_issuance_real
  from: stock_daily_real
  to: kzz_issuance_real
- bridge_steps: []
  description: null
  description_zh: stock_daily_real 到 kzz_conv_real，按截至时点关联
  from_node: stock_daily_real
  join_keys:
  - base: code
    source: market_code
  name: stock_daily_real_to_kzz_conv_real
  priority: 100
  relation_type: direct
  source_table: null
  time_binding:
    allow_equal: true
    available_time_field: null
    base_time_cast: date
    base_time_field: trade_time
    lookahead_safe: true
    mode: asof
    source_end_field: null
    source_start_field: null
    source_time_cast: null
    source_time_field: ann_date
  to_node: kzz_conv_real
  from: stock_daily_real
  to: kzz_conv_real
