nodes:
- asset_type: stock
  base_filters: []
  description: null
  description_zh: 股票日频宽表
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - pre_close
  - volume
  - amount
  - is_st
  - is_suspended
  - is_wd_sec
  - is_xr_sec
  - is_kcb
  - is_cyb
  - is_bjs
  - high_limited
  - low_limited
  - backward_adj_factor
  - market_cap
  - float_market_cap
  - turnover_rate
  grain: daily
  name: stock_daily_real
  node_role: query_entry
  query_freq: 1d
  status: enabled
  table: starlight.stock_daily_real
  time_key: trade_time
  wide_table:
    created_at: '2026-04-21T21:43:50'
    engine: Memory
    id: wide::stock_daily_real::c83034b0
    key_fields:
    - code
    - trade_time
    order_by:
    - code
    - trade_time
    partition_by: []
    source_node: stock_daily_real
    status: enabled
    sync_task: daily_kline
    updated_at: '2026-04-21T21:43:50'
    version_field: ''
- asset_type: null
  base_filters: []
  description: null
  description_zh: 股票分钟行情主表
  entity_keys:
  - code
  fields:
  - code
  - trade_time
  - open
  - high
  - low
  - close
  - volume
  - amount
  grain: minute
  name: stock_minute_real
  node_role: query_entry
  query_freq: null
  status: enabled
  table: starlight.ad_market_kline_minute
  time_key: trade_time
  wide_table: null
- asset_type: null
  base_filters: []
  description: null
  description_zh: 分红送配表
  entity_keys:
  - market_code
  fields:
  - ann_date
  - report_period
  - div_progress
  - dvd_per_share_stk
  - dvd_per_share_pre_tax_cash
  - dvd_per_share_after_tax_cash
  - date_eqy_record
  - date_ex
  - date_dvd_payout
  - div_bonusrate
  - div_conversedrate
  - remark
  - div_target
  grain: daily
  name: dividend_real
  node_role: relation_support
  query_freq: null
  status: enabled
  table: starlight.ad_dividend
  time_key: ann_date
  wide_table: null
- asset_type: null
  base_filters: []
  description: null
  description_zh: 交易日历表
  entity_keys: []
  fields:
  - trade_date
  grain: daily
  name: trade_calendar_real
  node_role: reference
  query_freq: null
  status: enabled
  table: starlight.ad_trade_calendar
  time_key: trade_date
  wide_table: null
- asset_type: null
  base_filters: []
  description: null
  description_zh: 龙虎榜表
  entity_keys:
  - market_code
  fields:
  - market_code
  - trade_date
  - security_name
  - reason_type
  - reason_type_name
  - change_range
  - trader_name
  - buy_amount
  - sell_amount
  - flow_mark
  - total_amount
  - total_volume
  grain: daily
  name: long_hu_bang_real
  node_role: query_entry
  query_freq: null
  status: enabled
  table: starlight.ad_long_hu_bang
  time_key: trade_date
  wide_table: null
edges: []
